name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: echobotbb.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image
        run: |
          docker build . -t echobotbb.azurecr.io/echobot:${{ github.sha }}
          docker build . -t echobotbb.azurecr.io/echobot:latest
          docker push echobotbb.azurecr.io/echobot:${{ github.sha }}
          docker push echobotbb.azurecr.io/echobot:latest
