name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: echobotbb.azurecr.io

      - name: Build and push container image
        run: |
          docker build . -t echobotbb.azurecr.io/echobot:${{ github.sha }}
          docker build . -t echobotbb.azurecr.io/echobot:latest
          docker push echobotbb.azurecr.io/echobot:${{ github.sha }}
          docker push echobotbb.azurecr.io/echobot:latest
